# Generated by Django 3.2 on 2022-12-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smartapp', '0002_alter_profil_shahar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='shahar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smartapp.shahar'),
        ),
    ]
